# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michal/Documents/Projekty/GBaric_cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michal/Documents/Projekty/GBaric_cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michal/Documents/Projekty/GBaric_cmake/CMakeFiles /home/michal/Documents/Projekty/GBaric_cmake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michal/Documents/Projekty/GBaric_cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GBaric

# Build rule for target.
GBaric: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GBaric
.PHONY : GBaric

# fast build rule for target.
GBaric/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/build
.PHONY : GBaric/fast

src/ApplicationBase.o: src/ApplicationBase.cpp.o
.PHONY : src/ApplicationBase.o

# target to build an object file
src/ApplicationBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/ApplicationBase.cpp.o
.PHONY : src/ApplicationBase.cpp.o

src/ApplicationBase.i: src/ApplicationBase.cpp.i
.PHONY : src/ApplicationBase.i

# target to preprocess a source file
src/ApplicationBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/ApplicationBase.cpp.i
.PHONY : src/ApplicationBase.cpp.i

src/ApplicationBase.s: src/ApplicationBase.cpp.s
.PHONY : src/ApplicationBase.s

# target to generate assembly for a file
src/ApplicationBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/ApplicationBase.cpp.s
.PHONY : src/ApplicationBase.cpp.s

src/GBaric.o: src/GBaric.cpp.o
.PHONY : src/GBaric.o

# target to build an object file
src/GBaric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GBaric.cpp.o
.PHONY : src/GBaric.cpp.o

src/GBaric.i: src/GBaric.cpp.i
.PHONY : src/GBaric.i

# target to preprocess a source file
src/GBaric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GBaric.cpp.i
.PHONY : src/GBaric.cpp.i

src/GBaric.s: src/GBaric.cpp.s
.PHONY : src/GBaric.s

# target to generate assembly for a file
src/GBaric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GBaric.cpp.s
.PHONY : src/GBaric.cpp.s

src/GMediaPlayer.o: src/GMediaPlayer.cpp.o
.PHONY : src/GMediaPlayer.o

# target to build an object file
src/GMediaPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GMediaPlayer.cpp.o
.PHONY : src/GMediaPlayer.cpp.o

src/GMediaPlayer.i: src/GMediaPlayer.cpp.i
.PHONY : src/GMediaPlayer.i

# target to preprocess a source file
src/GMediaPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GMediaPlayer.cpp.i
.PHONY : src/GMediaPlayer.cpp.i

src/GMediaPlayer.s: src/GMediaPlayer.cpp.s
.PHONY : src/GMediaPlayer.s

# target to generate assembly for a file
src/GMediaPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/GMediaPlayer.cpp.s
.PHONY : src/GMediaPlayer.cpp.s

src/Gui/GuiThread.o: src/Gui/GuiThread.cpp.o
.PHONY : src/Gui/GuiThread.o

# target to build an object file
src/Gui/GuiThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Gui/GuiThread.cpp.o
.PHONY : src/Gui/GuiThread.cpp.o

src/Gui/GuiThread.i: src/Gui/GuiThread.cpp.i
.PHONY : src/Gui/GuiThread.i

# target to preprocess a source file
src/Gui/GuiThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Gui/GuiThread.cpp.i
.PHONY : src/Gui/GuiThread.cpp.i

src/Gui/GuiThread.s: src/Gui/GuiThread.cpp.s
.PHONY : src/Gui/GuiThread.s

# target to generate assembly for a file
src/Gui/GuiThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Gui/GuiThread.cpp.s
.PHONY : src/Gui/GuiThread.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/MainWindow.o: src/MainWindow.cpp.o
.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/MainWindow.cpp.o
.PHONY : src/MainWindow.cpp.o

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/Memory/DBEngineBase.o: src/Memory/DBEngineBase.cpp.o
.PHONY : src/Memory/DBEngineBase.o

# target to build an object file
src/Memory/DBEngineBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DBEngineBase.cpp.o
.PHONY : src/Memory/DBEngineBase.cpp.o

src/Memory/DBEngineBase.i: src/Memory/DBEngineBase.cpp.i
.PHONY : src/Memory/DBEngineBase.i

# target to preprocess a source file
src/Memory/DBEngineBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DBEngineBase.cpp.i
.PHONY : src/Memory/DBEngineBase.cpp.i

src/Memory/DBEngineBase.s: src/Memory/DBEngineBase.cpp.s
.PHONY : src/Memory/DBEngineBase.s

# target to generate assembly for a file
src/Memory/DBEngineBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DBEngineBase.cpp.s
.PHONY : src/Memory/DBEngineBase.cpp.s

src/Memory/DataObject.o: src/Memory/DataObject.cpp.o
.PHONY : src/Memory/DataObject.o

# target to build an object file
src/Memory/DataObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DataObject.cpp.o
.PHONY : src/Memory/DataObject.cpp.o

src/Memory/DataObject.i: src/Memory/DataObject.cpp.i
.PHONY : src/Memory/DataObject.i

# target to preprocess a source file
src/Memory/DataObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DataObject.cpp.i
.PHONY : src/Memory/DataObject.cpp.i

src/Memory/DataObject.s: src/Memory/DataObject.cpp.s
.PHONY : src/Memory/DataObject.s

# target to generate assembly for a file
src/Memory/DataObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/DataObject.cpp.s
.PHONY : src/Memory/DataObject.cpp.s

src/Memory/FileManagerBase.o: src/Memory/FileManagerBase.cpp.o
.PHONY : src/Memory/FileManagerBase.o

# target to build an object file
src/Memory/FileManagerBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/FileManagerBase.cpp.o
.PHONY : src/Memory/FileManagerBase.cpp.o

src/Memory/FileManagerBase.i: src/Memory/FileManagerBase.cpp.i
.PHONY : src/Memory/FileManagerBase.i

# target to preprocess a source file
src/Memory/FileManagerBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/FileManagerBase.cpp.i
.PHONY : src/Memory/FileManagerBase.cpp.i

src/Memory/FileManagerBase.s: src/Memory/FileManagerBase.cpp.s
.PHONY : src/Memory/FileManagerBase.s

# target to generate assembly for a file
src/Memory/FileManagerBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/FileManagerBase.cpp.s
.PHONY : src/Memory/FileManagerBase.cpp.s

src/Memory/MemoryStream.o: src/Memory/MemoryStream.cpp.o
.PHONY : src/Memory/MemoryStream.o

# target to build an object file
src/Memory/MemoryStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/MemoryStream.cpp.o
.PHONY : src/Memory/MemoryStream.cpp.o

src/Memory/MemoryStream.i: src/Memory/MemoryStream.cpp.i
.PHONY : src/Memory/MemoryStream.i

# target to preprocess a source file
src/Memory/MemoryStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/MemoryStream.cpp.i
.PHONY : src/Memory/MemoryStream.cpp.i

src/Memory/MemoryStream.s: src/Memory/MemoryStream.cpp.s
.PHONY : src/Memory/MemoryStream.s

# target to generate assembly for a file
src/Memory/MemoryStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/MemoryStream.cpp.s
.PHONY : src/Memory/MemoryStream.cpp.s

src/Memory/Storage.o: src/Memory/Storage.cpp.o
.PHONY : src/Memory/Storage.o

# target to build an object file
src/Memory/Storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/Storage.cpp.o
.PHONY : src/Memory/Storage.cpp.o

src/Memory/Storage.i: src/Memory/Storage.cpp.i
.PHONY : src/Memory/Storage.i

# target to preprocess a source file
src/Memory/Storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/Storage.cpp.i
.PHONY : src/Memory/Storage.cpp.i

src/Memory/Storage.s: src/Memory/Storage.cpp.s
.PHONY : src/Memory/Storage.s

# target to generate assembly for a file
src/Memory/Storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Memory/Storage.cpp.s
.PHONY : src/Memory/Storage.cpp.s

src/Players/Gst/GstPipelineBase.o: src/Players/Gst/GstPipelineBase.cpp.o
.PHONY : src/Players/Gst/GstPipelineBase.o

# target to build an object file
src/Players/Gst/GstPipelineBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineBase.cpp.o
.PHONY : src/Players/Gst/GstPipelineBase.cpp.o

src/Players/Gst/GstPipelineBase.i: src/Players/Gst/GstPipelineBase.cpp.i
.PHONY : src/Players/Gst/GstPipelineBase.i

# target to preprocess a source file
src/Players/Gst/GstPipelineBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineBase.cpp.i
.PHONY : src/Players/Gst/GstPipelineBase.cpp.i

src/Players/Gst/GstPipelineBase.s: src/Players/Gst/GstPipelineBase.cpp.s
.PHONY : src/Players/Gst/GstPipelineBase.s

# target to generate assembly for a file
src/Players/Gst/GstPipelineBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineBase.cpp.s
.PHONY : src/Players/Gst/GstPipelineBase.cpp.s

src/Players/Gst/GstPipelineObj.o: src/Players/Gst/GstPipelineObj.cpp.o
.PHONY : src/Players/Gst/GstPipelineObj.o

# target to build an object file
src/Players/Gst/GstPipelineObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineObj.cpp.o
.PHONY : src/Players/Gst/GstPipelineObj.cpp.o

src/Players/Gst/GstPipelineObj.i: src/Players/Gst/GstPipelineObj.cpp.i
.PHONY : src/Players/Gst/GstPipelineObj.i

# target to preprocess a source file
src/Players/Gst/GstPipelineObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineObj.cpp.i
.PHONY : src/Players/Gst/GstPipelineObj.cpp.i

src/Players/Gst/GstPipelineObj.s: src/Players/Gst/GstPipelineObj.cpp.s
.PHONY : src/Players/Gst/GstPipelineObj.s

# target to generate assembly for a file
src/Players/Gst/GstPipelineObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstPipelineObj.cpp.s
.PHONY : src/Players/Gst/GstPipelineObj.cpp.s

src/Players/Gst/GstVideoPlayer.o: src/Players/Gst/GstVideoPlayer.cpp.o
.PHONY : src/Players/Gst/GstVideoPlayer.o

# target to build an object file
src/Players/Gst/GstVideoPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstVideoPlayer.cpp.o
.PHONY : src/Players/Gst/GstVideoPlayer.cpp.o

src/Players/Gst/GstVideoPlayer.i: src/Players/Gst/GstVideoPlayer.cpp.i
.PHONY : src/Players/Gst/GstVideoPlayer.i

# target to preprocess a source file
src/Players/Gst/GstVideoPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstVideoPlayer.cpp.i
.PHONY : src/Players/Gst/GstVideoPlayer.cpp.i

src/Players/Gst/GstVideoPlayer.s: src/Players/Gst/GstVideoPlayer.cpp.s
.PHONY : src/Players/Gst/GstVideoPlayer.s

# target to generate assembly for a file
src/Players/Gst/GstVideoPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/Gst/GstVideoPlayer.cpp.s
.PHONY : src/Players/Gst/GstVideoPlayer.cpp.s

src/Players/VlcPlayer/VlcMemoryPlayer.o: src/Players/VlcPlayer/VlcMemoryPlayer.cpp.o
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.o

# target to build an object file
src/Players/VlcPlayer/VlcMemoryPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcMemoryPlayer.cpp.o
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.cpp.o

src/Players/VlcPlayer/VlcMemoryPlayer.i: src/Players/VlcPlayer/VlcMemoryPlayer.cpp.i
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.i

# target to preprocess a source file
src/Players/VlcPlayer/VlcMemoryPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcMemoryPlayer.cpp.i
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.cpp.i

src/Players/VlcPlayer/VlcMemoryPlayer.s: src/Players/VlcPlayer/VlcMemoryPlayer.cpp.s
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.s

# target to generate assembly for a file
src/Players/VlcPlayer/VlcMemoryPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcMemoryPlayer.cpp.s
.PHONY : src/Players/VlcPlayer/VlcMemoryPlayer.cpp.s

src/Players/VlcPlayer/VlcPlayerBase.o: src/Players/VlcPlayer/VlcPlayerBase.cpp.o
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.o

# target to build an object file
src/Players/VlcPlayer/VlcPlayerBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcPlayerBase.cpp.o
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.cpp.o

src/Players/VlcPlayer/VlcPlayerBase.i: src/Players/VlcPlayer/VlcPlayerBase.cpp.i
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.i

# target to preprocess a source file
src/Players/VlcPlayer/VlcPlayerBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcPlayerBase.cpp.i
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.cpp.i

src/Players/VlcPlayer/VlcPlayerBase.s: src/Players/VlcPlayer/VlcPlayerBase.cpp.s
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.s

# target to generate assembly for a file
src/Players/VlcPlayer/VlcPlayerBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/Players/VlcPlayer/VlcPlayerBase.cpp.s
.PHONY : src/Players/VlcPlayer/VlcPlayerBase.cpp.s

src/RenderSurface.o: src/RenderSurface.cpp.o
.PHONY : src/RenderSurface.o

# target to build an object file
src/RenderSurface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/RenderSurface.cpp.o
.PHONY : src/RenderSurface.cpp.o

src/RenderSurface.i: src/RenderSurface.cpp.i
.PHONY : src/RenderSurface.i

# target to preprocess a source file
src/RenderSurface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/RenderSurface.cpp.i
.PHONY : src/RenderSurface.cpp.i

src/RenderSurface.s: src/RenderSurface.cpp.s
.PHONY : src/RenderSurface.s

# target to generate assembly for a file
src/RenderSurface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBaric.dir/build.make CMakeFiles/GBaric.dir/src/RenderSurface.cpp.s
.PHONY : src/RenderSurface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GBaric"
	@echo "... src/ApplicationBase.o"
	@echo "... src/ApplicationBase.i"
	@echo "... src/ApplicationBase.s"
	@echo "... src/GBaric.o"
	@echo "... src/GBaric.i"
	@echo "... src/GBaric.s"
	@echo "... src/GMediaPlayer.o"
	@echo "... src/GMediaPlayer.i"
	@echo "... src/GMediaPlayer.s"
	@echo "... src/Gui/GuiThread.o"
	@echo "... src/Gui/GuiThread.i"
	@echo "... src/Gui/GuiThread.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/Memory/DBEngineBase.o"
	@echo "... src/Memory/DBEngineBase.i"
	@echo "... src/Memory/DBEngineBase.s"
	@echo "... src/Memory/DataObject.o"
	@echo "... src/Memory/DataObject.i"
	@echo "... src/Memory/DataObject.s"
	@echo "... src/Memory/FileManagerBase.o"
	@echo "... src/Memory/FileManagerBase.i"
	@echo "... src/Memory/FileManagerBase.s"
	@echo "... src/Memory/MemoryStream.o"
	@echo "... src/Memory/MemoryStream.i"
	@echo "... src/Memory/MemoryStream.s"
	@echo "... src/Memory/Storage.o"
	@echo "... src/Memory/Storage.i"
	@echo "... src/Memory/Storage.s"
	@echo "... src/Players/Gst/GstPipelineBase.o"
	@echo "... src/Players/Gst/GstPipelineBase.i"
	@echo "... src/Players/Gst/GstPipelineBase.s"
	@echo "... src/Players/Gst/GstPipelineObj.o"
	@echo "... src/Players/Gst/GstPipelineObj.i"
	@echo "... src/Players/Gst/GstPipelineObj.s"
	@echo "... src/Players/Gst/GstVideoPlayer.o"
	@echo "... src/Players/Gst/GstVideoPlayer.i"
	@echo "... src/Players/Gst/GstVideoPlayer.s"
	@echo "... src/Players/VlcPlayer/VlcMemoryPlayer.o"
	@echo "... src/Players/VlcPlayer/VlcMemoryPlayer.i"
	@echo "... src/Players/VlcPlayer/VlcMemoryPlayer.s"
	@echo "... src/Players/VlcPlayer/VlcPlayerBase.o"
	@echo "... src/Players/VlcPlayer/VlcPlayerBase.i"
	@echo "... src/Players/VlcPlayer/VlcPlayerBase.s"
	@echo "... src/RenderSurface.o"
	@echo "... src/RenderSurface.i"
	@echo "... src/RenderSurface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

